version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: apigo
      DB_USER: postgres
      DB_PASSWORD: 123456
      JWT_SECRET_KEY: miClaveSecretaSuperSegura123!
      JWT_EXPIRATION: 24h
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apigo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: